# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: azkeever <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/07/02 15:54:43 by azkeever          #+#    #+#              #
#    Updated: 2018/07/02 15:59:12 by azkeever         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all: do-op

do-op: 
	gcc -Wall -Werror -Wextra -o do-op do_op.c ft_atoi.c val.c

clean: do-op
	rm -rf do-op *.swp
